name: compact

out_dir: "data/raw"
adj_close: true

equities: ["SPY", "IEFA", "IEMG", "IAU"]   # IEFA = Developed ex-US (ohne Kanada), IEMG = Emerging Markets, IAU = Gold
crypto:   ["BTC-USD", "ETH-USD"]
