name: regions
out_dir: "data/raw"
adj_close: true

equities: ["SPY", "IEUR", "EWJ", "IEMG","EWC", "IAU"]   # IEUR = Europa, EWJ = Japan, IEMG = Emerging Markets, SXR2 = Kanada,  IAU = Gold
crypto:   ["BTC-USD", "ETH-USD"]
