source: tiingo          # Primärquelle (tiingo)
interval: 1d            # Daily bars

bar_type: time          # (später: dollar/volume/imbalance)
prefer_intraday: false  # Intraday später anschließbar
exec_price: open_next   # Referenzpreis für T+1-Ausführung (alternativ: vwap_next)

return_type: log        # für return_raw (log oder linear)

fields:                 # Rohfelder, die wir aus der API holen
  - open
  - high
  - low
  - close
  - adj_close
  - volume
  - dividends
  - stock_splits

paths:
  raw_dir: data/raw
  interim_dir: data/interim
  clean_dir: data/clean

align:
  calendar: XNYS
  ffill_crypto: false

windows:
  adv: 20
  sma: [20, 60]
  ema: [12, 26]
  rsi: 14
  macd: [12, 26, 9]
  boll: [20, 2.0]
  cci: 20
  adx: 14

cs:
  sample_length: 1

risk_free:
  series_id: DFF
  day_count: 360

cash:
  symbol: CASH

feature_version: v1

