- _name: E2 #Baseline
  n_epochs: 12
  gae_lambda: 0.95
  vf_coef: 0.75
  learning_rate: 0.00040
  clip_range: 0.25
  clip_range_vf: 0.20
  target_kl: 0.016
  gamma: 0.99
  n_steps: 4096
  batch_size: 256
  use_sde: true
  sde_sample_freq: 4
  ent_coef: 0.0002

- _name: F1_E2_less_lambda
  n_epochs: 12
  gae_lambda: 0.93
  vf_coef: 0.75
  learning_rate: 0.00040
  clip_range: 0.25
  clip_range_vf: 0.20
  target_kl: 0.016
  gamma: 0.99
  n_steps: 4096
  batch_size: 256
  use_sde: true
  sde_sample_freq: 4
  ent_coef: 0.0002

- _name: F2_E2_higher_gamma
  n_epochs: 12
  gae_lambda: 0.95
  vf_coef: 0.75
  learning_rate: 0.00040
  clip_range: 0.25
  clip_range_vf: 0.20
  target_kl: 0.016
  gamma: 0.992
  n_steps: 4096
  batch_size: 256
  use_sde: true
  sde_sample_freq: 4
  ent_coef: 0.0002

- _name: F3_E2_bigger_sample
  n_epochs: 12
  gae_lambda: 0.95
  vf_coef: 0.75
  learning_rate: 0.00040
  clip_range: 0.25
  clip_range_vf: 0.20
  target_kl: 0.020
  gamma: 0.99
  n_steps: 4608
  batch_size: 256
  use_sde: true
  sde_sample_freq: 4
  ent_coef: 0.0002